# Generated by Django 5.0.3 on 2024-03-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('especie', models.CharField(max_length=200)),
                ('raza', models.CharField(max_length=200)),
                ('ocupacion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('habilidades', models.JSONField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
